random_text = [
    "Cool, I'm on it sir",
    "Just wait a second sir",
    "Okay sir, I'm working on it",
    "Right away, sir",
    "Please hold on, sir",
    "Let me check that for you",
    "Give me a moment, sir",
    "One moment please",
    "I'll have it ready shortly, sir",
    "Just a moment, sir",
    "I'll get to it right now, sir",
    "I'm handling that for you, sir",
    "Allow me a second, sir",
    "Working on it, sir",
    "Consider it done, sir",
    "On it right now, sir",
    "Let me do that for you, sir",
    "I'll take care of it, sir",
    "Just a sec, sir",
    "I'm taking care of it, sir",
    "At your service, sir",
    "Systems are go, processing now",
    "Scanning databases, please wait",
    "Initiating sequence, sir",
    "Always a pleasure to help, sir",
]
